version: "3.9"
services:
  node:
    ports:
      - 8080:3000
    image: ma_super_app
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mydatabase
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
